name: Build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build project

    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.412'

      - name: Run build
        run:
          dotnet build -c Release AzureBillingExporter.sln

      - name: Run unit-tests
        run: dotnet test --no-build -c Release ./AzureBillingExporter.Tests/AzureBillingExporter.Tests.csproj
